name: CI + CD

on: [push]

jobs:
    tests:
        name: Testing project
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [13.x, 14.x, 15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install yarn
              run: npm install -g yarn
            - name: Install all dependencies
              run: yarn install
            - name: Test the source code
              run: yarn run test --collect-coverage
            - uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

    deploy:
        name: Deploying the project to Github pages
        runs-on: ubuntu-latest
        needs: [tests]
        if: "contains(github.ref, 'master')"
        steps:
            - name: Check out the code
              uses: actions/checkout@v2
            - name: Use Node.js 15.x
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x
            - name: Install yarn
              run: npm install -g yarn
            - name: Install all dependencies
              run: yarn install
            - name: Build the source code
              run: yarn run build --public-url ./
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
